plugins { id 'com.android.application' }
android {
    namespace 'mk.workfashion.personal'
    compileSdk 35
    defaultConfig {
        applicationId 'mk.workfashion.personal'
        minSdk 26
        targetSdk 35
        versionCode 10
        versionName '1.9'
        testInstrumentationRunner 'mk.workfashion.personal.SmokeInstrumentation'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
dependencies {
    implementation 'org.mapsforge:mapsforge-map-android:0.25.0'
    implementation 'org.mapsforge:mapsforge-themes:0.25.0'
}
