plugins { id 'com.android.application' }
android {
    namespace 'mk.workfashion.personal'
    compileSdk 35
    defaultConfig {
        applicationId 'mk.workfashion.personal'
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName '1.1'
        testInstrumentationRunner 'mk.workfashion.personal.SmokeInstrumentation'
    }
    buildTypes { release { minifyEnabled false } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
}
